baseURL = "http://spencertn.com/"
languageCode = "en-us"
title = "The City of Spencer, Tennessee"
theme = "spencer"

[params]
  header = "Spencer Tennessee"
  description = "A Small City on the Cumberland Plateau"

[permalinks]
  updates = "/:year/:month/:title/"

[menu]

  [[menu.main]]
    identifier = "vanburencounty"
    name = "Van Buren County"
    url = "http://www.vanburencountytn.com/"
    parent = "Government"

  [[menu.main]]
    identifier = "tennessee"
    name = "State Government"
    url = "https://www.tn.gov/"
    parent = "Government"
