name = "Spencer"
license = ""
licenselink = ""
description = ""
homepage = "https://github.com/badsirbrian/spencer/"
tags = ["blog", "plain", "blank", "starter", "development"]
features = ["blog"]
min_version = "0.11111111"

[author]
  name = "badsirbrian"
  homepage = "https://github.com/badsirbiran"
